# Site settings
title: Keyboard Fire Blog
email: andy@keyboardfire.com
description: > # this means to ignore newlines until "baseurl:"
    A personal blog about programming and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.keyboardfire.com" # the base hostname & protocol for your site
twitter_username: KeyboardFire
github_username: KeyboardFire

# Build settings
markdown: kramdown

keep_files: ["_assets"]
